# Global Options ##################################################################################
directory: ~/beets-music # Destination
library: ~/.config/beets/library.db
pluginpath:                  # Directories to search for plugins. 
  - ~/.config/beets/plugins
include: # A space-separated list of extra configuration files to include.
  # Configuration files doesn't work if they are placed in sub folders.
  - secrets.yaml # Secret strings like usernames and passwords.
  - plugins.yaml # Activate/deactivate plugins here.
  # Contextual based configuration files. #######
  # See "plugins.yaml" file for plugin descriptions.
  - bandcamp.yaml
  - convert.yaml
  - discogs.yaml
  - duplicates.yaml
  - lastfm.yaml # All Last.fm related configurations.
  - lyrics.yaml
  - match.yaml
  - missing.yaml
  - muspy.yaml
  - oldestdate.yaml
  - paths.yaml # File and path related configurations.
  - pictures.yaml # Covers, artist images etc. Inludes plugin "extrafiles".
  - permissions.yaml
  - replace.yaml
  - replaygain.yaml
  - scrub.yaml
  - types.yaml
  - zero.yaml
#################################################

#clutter: yes                # When beets imports all the files in a directory, it tries to remove the directory if it’s empty.
                             # A directory is considered empty if it only contains files whose names match the glob patterns in clutter,
                             # which should be a list of strings. The default list consists of “Thumbs.DB” and “.DS_Store”.
                             # The importer only removes recursively searched subdirectories—the top-level directory you specify on the command line is never deleted.
original_date: yes           # Use the original date for the release.
per_disc_numbering: yes      # The track numbers are incremented throughout a multi disk release.
verbose: yes
threaded: yes                # Indicating whether the autotagger should use multiple threads.
                             # This makes things substantially faster by overlapping work
