# Edit this file to fit your system.

directory: /mnt/Music # Destination.
library: /mnt/Music/library.db
pluginpath:
  - ~/.config/beets/beetsplug/fetchartist
  - ~/.config/beets/beetsplug/discogs_extradata
