# Edit this file to fit your system.

directory: ~/beets-music # Destination.
library: ~/.config/beets/library.db
pluginpath:
  - ~/.config/beets/beetsplug/fetchartist
  - ~/.config/beets/beetsplug/discogs_extradata
