# Edit this file to fit your system.

directory: /mnt/Music/Beets-Test # Destination for testing.
#directory: /mnt/Music # Destination.
library: ~/.config/beets/library.db
pluginpath:
  - ~/.config/beets/beetsplug/fetchartist
  - ~/.config/beets/beetsplug/discogs_extradata
